introduction_rules = {
    "introduction": [
        "#IMade# #anIncredible# #breakthrough# in my research of #ELEMENT_NAME.capitalize# Magic, #resultingIn# #aNewSpell#.",
        "#whatADay#! My #foray# into #ELEMENT_NAME.capitalize# Magic #hasLedToANewSpell#.",
        "#todayWas# #unforgettable#! #AfterMonthsOfStudy#, I #haveFinally# #uncovered# #aNewSpell# in #ELEMENT_NAME.capitalize# Magic.",
        "In my #quest# to #master# #ELEMENT_NAME.capitalize# Magic, I #stumbledUpon# #aRemarkable# #discovery#.",
        "#IMustRecordThis#—#myExperiments# with #ELEMENT_NAME.capitalize# Magic #haveYielded# #aBreathtaking#, #remarkable# #result#.",
        "At long last, my #dedication# to #ELEMENT_NAME.capitalize# Magic #hasBorneFruit#, #resultingIn# #aNewSpell#.",
        "#SurprisingEvent#! While #experimenting# with #ELEMENT_NAME.capitalize# Magic, I #haveCreated# #spell.a# unlike any other.",
        "Today marks a #milestone# in my studies of #ELEMENT_NAME.capitalize# Magic, as I #haveCreated# #anExtraordinary# #spell#.",
        "My #quest# into #ELEMENT_NAME.capitalize# Magic #reachedANewHeight# today #withTheCreationOf# #powerful.a# #spell#.",
        "I #couldHardlyBelieveMyEyes# when, during my #exploration# of #ELEMENT_NAME.capitalize# Magic, I #created# #anIncredibleSpell#.",
    ],
    "couldHardlyBelieveMyEyes": [
        "could hardly believe my eyes",
        "was amazed",
        "was taken aback",
    ],
    "anIncredibleSpell": [
        "#anIncredible# #spell#",
        "#aBreathtaking# #spell#",
        "#spell.a# of #great# #power#",
    ],
    "reachedANewHeight": [
        "reached a new height",
        "ascended to new levels",
        "achieved unprecedented success",
    ],
    "withTheCreationOf": [
        "with the #development# of",
        "by the #development# of",
        "through the #development# of",
        "by #crafting#",
    ],
    "milestone": [
        "milestone",
        "pivotal moment",
        "significant point",
        "turning point",
        "landmark",
        "watershed moment",
        "momentous occasion",
        "historic event",
        "epoch-making discovery",
    ],
    "SurprisingEvent": [
        "A surprising turn of events, indeed",
        "To my astonishment, a most #breathtaking# event occurred",
        "Unexpectedly, a #remarkable# event took place",
        "To my surprise, a most #remarkable# event unfolded",
        "A most #extraordinary# event occurred",
    ],
    "experimenting": [  # experimenting with
        "experimenting",
        "tinkering",
        "dabbling",
        "fiddling",
        "playing",
        "working",
        "toying",
        "meddling",
        "engaging",
    ],
    "haveCreated": ["have #created#"],
    "created": [
        "created",
        "conjured",
        "brought forth",
        "discovered",
        "unearthed",
        "found",
        "manifested",
        "realized",
        "successfully developed",
        "magically crafted",
    ],
    "hasBorneFruit": [
        "has borne fruit",
        "is rewarded",
        "has paid off",
        "has come to fruition",
        "has yielded results",
    ],
    "IMustRecordThis": [
        "I am eager to share",
        "I cannot let this go unrecorded",
        "I feel compelled to document",
        "I must make a note of this",
        "I must make note of this",
        "I must preserve this moment",
        "I must put pen to paper and record",
        "I must record this",
        "It is imperative that I record",
        "It is of the utmost importance that I record",
        "Let it be known",
        "This must be documented",
    ],
    "myExperiments": ["My experiments", "Recent tests", "My trials"],
    "haveYielded": [
        "have yielded",
        "resulted in",
        "produced",
        "have produced",
        "have brought forth",
    ],
    "result": ["result", "outcome", "effect"],
    "master": ["master", "tame", "control"],
    "quest": ["quest", "journey", "pursuit", "undertaking", "exploration"],
    "stumbledUpon": ["stumbled upon", "unearthed", "happened upon"],
    "todayWas": ["Today was", "This day has been", "It has been"],
    "unforgettable": ["unforgettable", "astonishing", "remarkable"],
    "AfterMonthsOfStudy": [
        "After months of study",
        "Following extensive research",
        "After tireless efforts",
    ],
    "haveFinally": ["have finally", "at last have", "have ultimately"],
    "uncovered": ["uncovered", "discovered", "revealed"],
    "hasLedToANewSpell": [
        "#hasRevealedOrLedMeTo# #aNewSpell#",
        "#hasLedMeTo# #theDiscoveryOfANewSpell#",
    ],
    "hasRevealedOrLedMeTo": ["#hasRevealed#", "#hasLedMeTo#"],
    "hasRevealed": [
        "has revealed",
        "has shown",
        "has unveiled",
        "has uncovered",
    ],
    "hasLedMeTo": [
        "has led me to",
        "has brought me to",
        "has guided me to",
    ],
    "resultingIn": [
        "resulting in",
        "culminating in",
        "leading to",
        "bringing about",
        "ushering in",
        "manifesting as",
    ],
    "whatADay": [
        "#ahoy.capitalize#, what a day to remember",
        "What a day to remember, #ahoy#",
        "What a day it has been, #ahoy#",
        "What a day of #breathtaking# discoveries, #ahoy#",
        "What #breathtaking.a# day, #ahoy#",
        "#ahoy.capitalize#! What a whirlwind of a day it has been",
        "Oh, what a whirlwind of a day it has been",
        "What #breathtaking.a# day",
        "What a day it has been",
        "What a day to remember",
        "What a day of #breathtaking# discoveries",
    ],
    "ahoy": [
        "ahoy",
        "stars" "heavens",
        "goodness",
        "my",
        "my word",
        "my stars",
        "my heavens",
        "my goodness",
        "oh",
        "oh my",
        "oh my stars",
        "oh my word",
        "oh my heavens",
        "oh my goodness",
        "dear me",
        "my oh my",
        "good heavens",
        "good gracious",
        "goodness gracious",
        "goodness me",
        "by the gods",
        "by the heavens",
        "by the stars",
        "by the heavens above",
        "by the stars above",
        "by the gods above",
        "by the heavens and stars",
        "by the stars and heavens",
        "by the heavens and stars above",
        "by the stars and heavens above",
    ],
    "IMade": [
        "Today, I made",
        "I am proud to announce that I have made",
        "I have made",
        "I made",
        "I am thrilled to share that I have made",
    ],
    "anIncredible": [
        "#spectacular.a#",
    ],
    "spectacular": ["incredible", "monumental", "spectacular"],
    "breakthrough": ["breakthrough", "#discovery#", "advancement"],
    "exploration": [  # exploration of
        "exploration",
        "study",
        "examination",
        "investigation",
        "analysis",
        "research",
    ],
    "foray": [  # foray into
        "experimentation",
        "foray",
        "exploration",
        "dabbling",
        "investigation",
        "study",
        "research",
        "pursuit",
        "quest",
    ],
    "theDiscoveryOfANewSpell": [
        "the #discovery# of #aNew# #spell#",
    ],
    "discovery": ["discovery", "finding", "revelation"],
    "aNewSpell": [
        "#aBreathtakingOrGreat#, #new# #spell#",
        "#aGreat# #spell#",
        "#spell.a# of #breathtakingOrGreat# #powerPotentialOrBeauty#",
    ],
    "breathtakingOrGreat": ["#breathtaking#", "#great#"],
    "aBreathtakingOrGreat": ["#aBreathtaking#", "#aGreat#"],
    "powerPotentialOrBeauty": ["#power#", "#potential#", "#beauty#"],
    "aNew": ["#new.a#"],
    "new": [
        "new",
        "novel",
        "unfamiliar",
        "unprecedented",
        "unexplored",
        "unseen",
        "undiscovered",
        "never-before-seen",
    ],
}

shared = {
    "aBreathtaking": ["#breathtaking.a#"],
    "breathtaking": [
        "breathtaking",
        "mesmerizing",
        "astonishing",
        "awe-inspiring",
        "ethereal",
        "enchanting",
        "captivating",
        "spellbinding",
        "magnificent",
        "stunning",
        "marvelous",
        "wondrous",
        "extraordinary",
        "impressive",
        "phenomenal",
    ],
    "aRemarkable": ["#remarkable.a#"],
    "remarkable": [
        "remarkable",
        "extraordinary",
        "noteworthy",
        "notable",
        "impressive",
        "exceptional",
        "outstanding",
        "significant",
        "striking",
        "memorable",
        "unusual",
        "unique",
        "uncommon",
        "rare",
        "unprecedented",
        "singular",
        "special",
        "unusual",
        "peculiar",
        "curious",
        "odd",
        "strange",
        "weird",
        "bizarre",
        "abnormal",
        "atypical",
        "anomalous",
        "deviant",
        "freakish",
        "perplexing",
        "puzzling",
        "mystifying",
        "baffling",
        "confounding",
        "bewildering",
        "enigmatic",
        "cryptic",
        "mysterious",
        "obscure",
        "arcane",
        "esoteric",
        "inscrutable",
        "incomprehensible",
        "unfathomable",
        "impenetrable",
        "unintelligible",
        "unaccountable",
    ],
    "anExtraordinary": ["#extraordinary.a#"],
    "extraordinary": [
        "extraordinary",
        "remarkable",
        "exceptional",
        "magnificent",
        "unparalleled",
        "outstanding",
        "impressive",
        "astonishing",
    ],
    "aGreat": ["#great.a#"],
    "great": ["great", "immense", "remarkable", "awe-inspiring", "awe-striking"],
    "power": ["power", "strength", "might", "force", "potency"],
    "powerful": ["powerful", "potent", "strong", "mighty"],
    "potential": ["potential", "possibilities"],
    "spell": ["spell", "incantation", "magic formula", "magical technique"],
    "beauty": ["beauty", "elegance", "grace", "splendor"],
    "dedication": ["dedication", "commitment", "devotion"],
    "crafting": ["crafting", "creating", "forming", "shaping", "molding"],
    "development": ["development", "creation", "formation"],
}

rules = {}
rules.update(introduction_rules)
rules.update(shared)
